version: '3.7'
services:
    dbpa:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
          - 5432:5432
        volumes: 
          # copy the sql script to create tables
          - ./scripts/seeding.sql:/docker-entrypoint-initdb.d/seeding.sql          
    web-node:
        build: .
        ports:
          - 8080:8080
        environment:
          - PGUSER=${PGUSER}
          - PGDATABASE=${PGDATABASE}
          - PGHOST=${PGHOST}
          - PGPASSWORD=${PGPASSWORD}
          - PGPORT=${PGPORT}
        depends_on:
          - dbpa